# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.GLMadj <- function(formula, categories_order, proportional_effects, data, distribution, freedom_degrees) {
    .Call(`_pack_GLMadj`, formula, categories_order, proportional_effects, data, distribution, freedom_degrees)
}

GLMcum <- function(formula, categories_order, proportional_effects, data, distribution, freedom_degrees, beta_init, threshold) {
    .Call(`_pack_GLMcum`, formula, categories_order, proportional_effects, data, distribution, freedom_degrees, beta_init, threshold)
}

All_pre_data_or2 <- function(formula, input_data, categories_order, proportional_effect) {
    .Call(`_pack_All_pre_data_or2`, formula, input_data, categories_order, proportional_effect)
}

.GLMref <- function(formula, categories_order, proportional_effects, data, distribution, freedom_degrees) {
    .Call(`_pack_GLMref`, formula, categories_order, proportional_effects, data, distribution, freedom_degrees)
}

.Predict_Response <- function(model_object, NEWDATA) {
    .Call(`_pack_Predict_Response`, model_object, NEWDATA)
}

.Discrete_CM <- function(formula, case_id, alternatives, reference, alternative_specific, data, distribution, freedom_degrees) {
    .Call(`_pack_Discrete_CM`, formula, case_id, alternatives, reference, alternative_specific, data, distribution, freedom_degrees)
}

GLMseq <- function(formula, categories_order, proportional_effects, data, distribution, freedom_degrees) {
    .Call(`_pack_GLMseq`, formula, categories_order, proportional_effects, data, distribution, freedom_degrees)
}

