# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LogisticMulti <- function(a, b) {
    .Call(`_pack_LogisticMulti`, a, b)
}

MultinomialRegressionAlgo <- function(X_M, Y_EXT, K) {
    .Call(`_pack_MultinomialRegressionAlgo`, X_M, Y_EXT, K)
}

timesTwo <- function(x) {
    .Call(`_pack_timesTwo`, x)
}

