# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GLMadj <- function(response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe) {
    .Call(`_pack_GLMadj`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe)
}

GLMcum <- function(response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe, beta_t, beta_init) {
    .Call(`_pack_GLMcum`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe, beta_t, beta_init)
}

GLMref <- function(response = "a", explanatory_complete = as.character( c( "A", NA_STRING)), explanatory_proportional = as.character( c( "A", NA_STRING)), distribution = "a", categories_order = as.character( c( "A", NA_STRING)), dataframe, freedom_degrees = 2.0) {
    .Call(`_pack_GLMref`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe, freedom_degrees)
}

GLMseq <- function(response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe) {
    .Call(`_pack_GLMseq`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe)
}

